/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maven_java_project;
import javax.swing.*;
import java.awt.*;
import javax.swing.border.Border;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Flo0w
 */
public class Ajouter extends javax.swing.JFrame {

    /**
     * Creates new form Ajouter
     */
    public Ajouter()  {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanelOrdi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jPanelTablette = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jComboBox9 = new javax.swing.JComboBox();
        jPanelRouteur = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox10 = new javax.swing.JComboBox();
        jPanelLocal = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldNL = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldAL = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jSpinnerNBS = new javax.swing.JSpinner();
        jPanelSalle = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter un équipement");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Ajouter ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Local", "Salle", "Equipement", "     Ordinateur", "     Tablette", "     Routeur" }));
        jComboBox1.setToolTipText("Sélectionner...");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Sélectionner ce que vous voulez ajouter...");

        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, "card5");

        jPanelOrdi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Ajouter un Ordinateur");

        jLabel6.setText("Nom de l'ordinateur :");

        jLabel7.setText("Adresse MAC :");

        jLabel8.setText("Emplacement :");

        jLabel9.setText("Système d'exploitation :");

        jLabel11.setText("Activer / Désactiver :");

        jButton3.setText("Valider");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Windows 7", "Windows 8", "Linux", "Mac" }));

        jLabel32.setText("Nom du firmware :");

        jComboBox6.setModel(getComboBoxModelSalle());

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        javax.swing.GroupLayout jPanelOrdiLayout = new javax.swing.GroupLayout(jPanelOrdi);
        jPanelOrdi.setLayout(jPanelOrdiLayout);
        jPanelOrdiLayout.setHorizontalGroup(
            jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdiLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrdiLayout.createSequentialGroup()
                .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOrdiLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelOrdiLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrdiLayout.createSequentialGroup()
                                    .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))
                                    .addGap(122, 122, 122))
                                .addComponent(jLabel8))
                            .addGroup(jPanelOrdiLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(134, 134, 134))
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelOrdiLayout.createSequentialGroup()
                                .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(79, 79, 79)
                                .addComponent(jLabel13))
                            .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox8, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(41, 41, 41))
        );
        jPanelOrdiLayout.setVerticalGroup(
            jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdiLayout.createSequentialGroup()
                .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrdiLayout.createSequentialGroup()
                        .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelOrdiLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelOrdiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOrdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11))
                    .addGroup(jPanelOrdiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanelOrdi, "ordi");

        jPanelTablette.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Ajouter une tablette");

        jButton2.setText("Valider");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Nom de la tablette :");

        jLabel12.setText("Adresse MAC :");

        jLabel14.setText("Emplacement :");

        jLabel15.setText("Système d'exploitation :");

        jLabel17.setText("Activer / Désactiver :");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Android", "iOS", "Windows" }));

        jComboBox4.setModel(getComboBoxModelSalle());

        jLabel16.setText("Nom du firmware :");

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        javax.swing.GroupLayout jPanelTabletteLayout = new javax.swing.GroupLayout(jPanelTablette);
        jPanelTablette.setLayout(jPanelTabletteLayout);
        jPanelTabletteLayout.setHorizontalGroup(
            jPanelTabletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabletteLayout.createSequentialGroup()
                .addGroup(jPanelTabletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTabletteLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel3))
                    .addGroup(jPanelTabletteLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanelTabletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addGroup(jPanelTabletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelTabletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTabletteLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelTabletteLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(jPanelTabletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jComboBox9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addComponent(jLabel18)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabletteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(92, 92, 92))
        );
        jPanelTabletteLayout.setVerticalGroup(
            jPanelTabletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabletteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(64, 64, 64)
                .addGroup(jPanelTabletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTabletteLayout.createSequentialGroup()
                        .addGroup(jPanelTabletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanelTabletteLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel10)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(76, 76, 76))
                    .addGroup(jPanelTabletteLayout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanelTablette, "tablette");

        jPanelRouteur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Ajouter un routeur");

        jLabel19.setText("Nom du routeur :");

        jLabel20.setText("Adresse MAC :");

        jLabel21.setText("Emplacement :");

        jLabel23.setText("Activer / Désactiver :");

        jButton4.setText("Valider");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(getComboBoxModelSalle());

        jLabel33.setText("Nom du firmware :");

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        javax.swing.GroupLayout jPanelRouteurLayout = new javax.swing.GroupLayout(jPanelRouteur);
        jPanelRouteur.setLayout(jPanelRouteurLayout);
        jPanelRouteurLayout.setHorizontalGroup(
            jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRouteurLayout.createSequentialGroup()
                .addGroup(jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRouteurLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel5))
                    .addGroup(jPanelRouteurLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addGroup(jPanelRouteurLayout.createSequentialGroup()
                                .addGroup(jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23))
                                .addGap(93, 93, 93)
                                .addGroup(jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField7)
                                    .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField10)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jComboBox10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRouteurLayout.createSequentialGroup()
                .addGap(256, 450, Short.MAX_VALUE)
                .addGroup(jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRouteurLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRouteurLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(38, 38, 38))))
        );
        jPanelRouteurLayout.setVerticalGroup(
            jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRouteurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(75, 75, 75)
                .addComponent(jLabel24)
                .addGap(17, 17, 17)
                .addGroup(jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRouteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(jButton4)
                .addGap(38, 38, 38))
        );

        jPanel1.add(jPanelRouteur, "routeur");

        jPanelLocal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setText("Ajouter un local");

        jLabel26.setText("Nom du local :");

        jButton5.setText("Valider");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel30.setText("Adresse du local :");

        jLabel31.setText("Nombre de salle(s) :");

        javax.swing.GroupLayout jPanelLocalLayout = new javax.swing.GroupLayout(jPanelLocal);
        jPanelLocal.setLayout(jPanelLocalLayout);
        jPanelLocalLayout.setHorizontalGroup(
            jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocalLayout.createSequentialGroup()
                .addGroup(jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLocalLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel25))
                    .addGroup(jPanelLocalLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(177, 177, 177)
                        .addGroup(jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNL, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextFieldAL)
                            .addGroup(jPanelLocalLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jSpinnerNBS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLocalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(91, 91, 91))
        );
        jPanelLocalLayout.setVerticalGroup(
            jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(55, 55, 55)
                .addGroup(jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextFieldAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jSpinnerNBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(81, 81, 81))
        );

        jPanel1.add(jPanelLocal, "local");

        jPanelSalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setText("Ajouter une salle");

        jLabel28.setText("Nom de la salle :");

        jLabel29.setText("Emplacement :");

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jButton6.setText("Valider");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(getComboBoxModelLocal());

        javax.swing.GroupLayout jPanelSalleLayout = new javax.swing.GroupLayout(jPanelSalle);
        jPanelSalle.setLayout(jPanelSalleLayout);
        jPanelSalleLayout.setHorizontalGroup(
            jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(73, 73, 73))
            .addGroup(jPanelSalleLayout.createSequentialGroup()
                .addGroup(jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSalleLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel27))
                    .addGroup(jPanelSalleLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(128, 128, 128)
                        .addGroup(jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField15)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanelSalleLayout.setVerticalGroup(
            jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(86, 86, 86)
                .addGroup(jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(65, 65, 65))
        );

        jPanel1.add(jPanelSalle, "salle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jComboBox1.getAccessibleContext().setAccessibleName("Sélectionner");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String valueBox = "";
        valueBox = (String)jComboBox1.getSelectedItem();
        if("     Ordinateur".equals(valueBox)){
            ((CardLayout)jPanel1.getLayout()).show(jPanel1,"ordi");
        }
        else if("     Tablette".equals(valueBox)){
            ((CardLayout)jPanel1.getLayout()).show(jPanel1,"tablette");
        }
        else if("     Routeur".equals(valueBox)){
            ((CardLayout)jPanel1.getLayout()).show(jPanel1, "routeur");
        }
        else if("Local".equals(valueBox)){
            ((CardLayout)jPanel1.getLayout()).show(jPanel1, "local");
        }
        else if("Salle".equals(valueBox)){
            ((CardLayout)jPanel1.getLayout()).show(jPanel1, "salle");
        }
        else{
            ((CardLayout)jPanel1.getLayout()).show(jPanel1, "card5");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.ajouterAppareil();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        if(this.verifEntreeLocal()){
            BDD bd = new BDD();
            bd.connect(); 
            String nomLoc = jTextFieldNL.getText();
            String addrLocal = jTextFieldAL.getText();
            int nbSLocal = (Integer)jSpinnerNBS.getValue(); 
            try {
                if(bd.exist("Local", "nomLocal", nomLoc)){
                    javax.swing.JOptionPane.showMessageDialog(null,"Le nom du local est déjà présent dans la base", "Erreur Saisie nom local", JOptionPane.ERROR_MESSAGE); 
                    jTextFieldNL.requestFocus(); 
                }
                else{
                    String req = "INSERT INTO Local (nomlocal, lieulocal, nbrsalle) VALUES ('" +nomLoc +"', '" +addrLocal+"', " +nbSLocal+");";
                    bd.request(req);
                    javax.swing.JOptionPane.showMessageDialog(null,"Le local " +nomLoc+ " a bien été ajouté dans la base !", "Succès", JOptionPane.PLAIN_MESSAGE); 
                    Principal princ = new Principal();
                    princ.setLocationRelativeTo(null);
                    this.setVisible(false);
                    princ.setVisible(true);

                }
            } catch (SQLException ex) {
                Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else{
            System.out.println("Problème insertion local");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(this.verifEntreeSalle()){
            try {
                BDD bd = new BDD();
                bd.connect();
                String nomS = jTextField15.getText();
                String valueBox = (String)jComboBox2.getSelectedItem();
                if(bd.exist("Salle", "nomSalle", nomS)){
                    javax.swing.JOptionPane.showMessageDialog(null,"Le nom de la salle est déjà présent dans la base", "Erreur Saisie nom salle", JOptionPane.ERROR_MESSAGE); 
                    jTextField15.requestFocus();                     
                }
                else{
                    String req = "INSERT INTO Salle (nomSalle, lieuSalle, nomLocal) VALUES ('" +nomS + "', '" +valueBox+"', '" +valueBox +"');";
                    bd.request(req);
                    javax.swing.JOptionPane.showMessageDialog(null,"La salle " +nomS+ " dans le local " +valueBox +" a bien été ajouté dans la base !", "Succès", JOptionPane.PLAIN_MESSAGE); 
                    Principal princ = new Principal();
                    princ.setLocationRelativeTo(null);
                    this.setVisible(false);
                    princ.setVisible(true);                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.ajouterAppareil();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.ajouterAppareil();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajouter().setVisible(true);
            }
        });
    }
    
    private boolean verifEntreeLocal(){
        String nomLoc = jTextFieldNL.getText();
        String addrLocal = jTextFieldAL.getText();
        int nbSLocal = (Integer)jSpinnerNBS.getValue();        
        if(nomLoc.length() > 32){
             javax.swing.JOptionPane.showMessageDialog(null,"Le nom du local est trop grand", "Erreur Saisie nom local", JOptionPane.ERROR_MESSAGE); 
             jTextFieldNL.requestFocus(); 
             return false;
        }
        if(addrLocal.length() > 32){
             javax.swing.JOptionPane.showMessageDialog(null,"L'adresse du local est trop grande", "Erreur Saisie adresse local", JOptionPane.ERROR_MESSAGE); 
             jTextFieldAL.requestFocus(); 
             return false;
        }
        if(nbSLocal < 1){
             javax.swing.JOptionPane.showMessageDialog(null,"Le nombre de Salle est incorrect", "Erreur Saisie nombre salle ", JOptionPane.ERROR_MESSAGE); 
             jSpinnerNBS.requestFocus();            
             return false;
        }
        return true;
        
    }
    
    private boolean verifEntreeSalle(){
        String nomSalle = jTextField15.getText();
        if(nomSalle.length() > 32){
             javax.swing.JOptionPane.showMessageDialog(null,"Le nom de la salle est trop grand", "Erreur Saisie nom salle", JOptionPane.ERROR_MESSAGE); 
             jTextField15.requestFocus(); 
             return false;
        }
        return true;
    }
    
    private boolean verifAddrMAC(String addr){
        if(addr.length() != 17){
            return false;
        }
        addr.toLowerCase();
        int i = 0;
        int val;
        while(i < addr.length()){
            val = (int)addr.charAt(i);
            if((val >= 97 && val <= 102) || (val >= 48 && val <= 57) || val == 58 ){
                i++;
            }
            else
            {
                return false;
            }
        }
        return true;
        
    }
    
    
    private boolean verifEntreeOrdi(){
        String nomO = jTextField1.getText();
        String addrM = jTextField2.getText();
        String nomFirm = jTextField4.getText();
        if(this.verifAddrMAC(addrM)){
            if(nomO.length() > 32)
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Le nom de l'ordinateur est trop grand", "Erreur Saisie nom ordi", JOptionPane.ERROR_MESSAGE); 
                jTextField1.requestFocus(); 
                return false; 
            }
            if(nomFirm.length() > 32)
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Le nom du firmware est trop grand", "Erreur Saisie nom firmware", JOptionPane.ERROR_MESSAGE); 
                jTextField4.requestFocus(); 
                return false;
            }
        }else{
             javax.swing.JOptionPane.showMessageDialog(null,"L'adresse MAC entrée n'est pas correcte", "Erreur Saisie adresse MAC", JOptionPane.ERROR_MESSAGE); 
             jTextField2.requestFocus(); 
             return false;            
        }
        
        return true;
       
    }
    
    private boolean verifEntreeTablette(){
        String nomT = jTextField5.getText();
        String addrM = jTextField6.getText();
        String nomFirm = jTextField8.getText();
        if(this.verifAddrMAC(addrM)){
            if(nomT.length() > 32)
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Le nom de la tablette est trop grand", "Erreur Saisie nom tablette", JOptionPane.ERROR_MESSAGE); 
                jTextField1.requestFocus(); 
                return false; 
            }
            if(nomFirm.length() > 32)
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Le nom du firmware est trop grand", "Erreur Saisie nom firmware", JOptionPane.ERROR_MESSAGE); 
                jTextField4.requestFocus(); 
                return false;
            }
        }else{
             javax.swing.JOptionPane.showMessageDialog(null,"L'adresse MAC entrée n'est pas correcte", "Erreur Saisie adresse MAC", JOptionPane.ERROR_MESSAGE); 
             jTextField2.requestFocus(); 
             return false;            
        }
        
        return true;
 }
    private boolean verifEntreeRouteur(){
         String nomR = jTextField10.getText();
        String addrM = jTextField11.getText();
        String nomFirm = jTextField7.getText();
        if(this.verifAddrMAC(addrM)){
            if(nomR.length() > 32)
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Le nom du routeur est trop grand", "Erreur Saisie nom routeur", JOptionPane.ERROR_MESSAGE); 
                jTextField1.requestFocus(); 
                return false; 
            }
            if(nomFirm.length() > 32)
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Le nom du firmware est trop grand", "Erreur Saisie nom firmware", JOptionPane.ERROR_MESSAGE); 
                jTextField4.requestFocus(); 
                return false;
            }
        }else{
             javax.swing.JOptionPane.showMessageDialog(null,"L'adresse MAC entrée n'est pas correcte", "Erreur Saisie adresse MAC", JOptionPane.ERROR_MESSAGE); 
             jTextField2.requestFocus(); 
             return false;            
        }
        
        return true;       
    }
    
    
    private void ajouterOrdi(){
        if(this.verifEntreeOrdi()){
            try {
                BDD bd = new BDD();
                bd.connect();
                String nomO = jTextField1.getText();
                String valueBoxOS = (String)jComboBox5.getSelectedItem();
                String valueBoxEmp = (String)jComboBox6.getSelectedItem();
                valueBoxEmp = valueBoxEmp.substring(5);
                String nomFirm = jTextField4.getText();
                String valueActive = (String)jComboBox8.getSelectedItem();
                String typeApp = (String)jComboBox1.getSelectedItem();
                String adrMac = jTextField2.getText();
                if(bd.exist("Appareil", "nomapp", nomO)){
                    javax.swing.JOptionPane.showMessageDialog(null,"Le nom de l'ordinateur est déjà présent dans la base", "Erreur Saisie nom ordi", JOptionPane.ERROR_MESSAGE); 
                    jTextField1.requestFocus();                     
                }
                else{
                    String req = "INSERT INTO Appareil (nomapp, typeappareil, systexpappareil, nomfirmware, active, lieuappareil, nomsalle) VALUES ('" +nomO + "', '" +typeApp+"', '" +valueBoxOS +"', '" +nomFirm+"', " +valueActive+", '" +valueBoxEmp+"', '" +valueBoxEmp+"');";
                    bd.request(req);
                    req = "INSERT INTO carte_reseau (adrmacappareil, nomapp) VALUES ('" +adrMac +"', '" +nomO+"');";
                    bd.request(req);
                    javax.swing.JOptionPane.showMessageDialog(null,"L'appareil " +nomO +" a bien été ajouté dans la base !", "Succès", JOptionPane.PLAIN_MESSAGE); 
                    Principal princ = new Principal();
                    princ.setLocationRelativeTo(null);
                    this.setVisible(false);
                    princ.setVisible(true);                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
            }
        }              
    }
    
    private void ajouterTablette(){
         if(this.verifEntreeTablette()){
            try {
                BDD bd = new BDD();
                bd.connect();
                String nomT = jTextField5.getText();
                String valueBoxOS = (String)jComboBox3.getSelectedItem();
                String valueBoxEmp = (String)jComboBox4.getSelectedItem();
                valueBoxEmp = valueBoxEmp.substring(5);
                String nomFirm = jTextField8.getText();
                String valueActive = (String)jComboBox9.getSelectedItem();
                String typeApp = (String)jComboBox1.getSelectedItem();
                String adrMac = jTextField6.getText();
                if(bd.exist("Appareil", "nomapp", nomT)){
                    javax.swing.JOptionPane.showMessageDialog(null,"Le nom de la tablette est déjà présent dans la base", "Erreur Saisie nom tablette", JOptionPane.ERROR_MESSAGE); 
                    jTextField1.requestFocus();                     
                }
                else{
                    String req = "INSERT INTO Appareil (nomapp, typeappareil, systexpappareil, nomfirmware, active, lieuappareil, nomsalle) VALUES ('" +nomT + "', '" +typeApp+"', '" +valueBoxOS +"', '" +nomFirm+"', " +valueActive+", '" +valueBoxEmp+"', '" +valueBoxEmp+"');";
                    bd.request(req);
                    req = "INSERT INTO carte_reseau (adrmacappareil, nomapp) VALUES ('" +adrMac +"', '" +nomT+"');";
                    bd.request(req);
                    javax.swing.JOptionPane.showMessageDialog(null,"L'appareil " +nomT +" a bien été ajouté dans la base !", "Succès", JOptionPane.PLAIN_MESSAGE); 
                    Principal princ = new Principal();
                    princ.setLocationRelativeTo(null);
                    this.setVisible(false);
                    princ.setVisible(true);                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }
    
    private void ajouterRouteur(){
          if(this.verifEntreeRouteur()){
            try {
                BDD bd = new BDD();
                bd.connect();
                String nomR = jTextField10.getText();
                String valueBoxOS = " ";
                String valueBoxEmp = (String)jComboBox7.getSelectedItem();
                valueBoxEmp = valueBoxEmp.substring(5);
                String nomFirm = jTextField7.getText();
                String valueActive = (String)jComboBox10.getSelectedItem();
                String typeApp = (String)jComboBox1.getSelectedItem();
                String adrMac = jTextField11.getText();
                if(bd.exist("Appareil", "nomapp", nomR)){
                    javax.swing.JOptionPane.showMessageDialog(null,"Le nom du routeur est déjà présent dans la base", "Erreur Saisie nom routeur", JOptionPane.ERROR_MESSAGE); 
                    jTextField1.requestFocus();                     
                }
                else{
                    String req = "INSERT INTO Appareil (nomapp, typeappareil, systexpappareil, nomfirmware, active, lieuappareil, nomsalle) VALUES ('" +nomR + "', '" +typeApp+"', '" +valueBoxOS +"', '" +nomFirm+"', " +valueActive+", '" +valueBoxEmp+"', '" +valueBoxEmp+"');";
                    bd.request(req);
                    req = "INSERT INTO carte_reseau (adrmacappareil, nomapp) VALUES ('" +adrMac +"', '" +nomR+"');";
                    bd.request(req);
                    javax.swing.JOptionPane.showMessageDialog(null,"L'appareil " +nomR +" a bien été ajouté dans la base !", "Succès", JOptionPane.PLAIN_MESSAGE); 
                    Principal princ = new Principal();
                    princ.setLocationRelativeTo(null);
                    this.setVisible(false);
                    princ.setVisible(true);                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }
    
    
    private void ajouterAppareil(){
        String type = (String)jComboBox1.getSelectedItem();
        if("     Ordinateur".equals(type)){
            this.ajouterOrdi();
        }
        else if("     Tablette".equals(type)){
            this.ajouterTablette();
        }
        else if ("     Routeur".equals(type)){
            this.ajouterRouteur();
        }
    
        
        
    }
    
    
    
    
    
    private ComboBoxModel getComboBoxModelLocal() {
    
        try {
            // TODO add your handling code here:
            BDD bd = new BDD();
            bd.connect();
            ResultSet resultats = bd.select("SELECT nomLocal FROM Local");
            String[] locaux = new String[100];
            int i = 0;
            while(resultats.next())
            {
                locaux[i] = resultats.getString(1);
                i++;
            }
            String[] item = new String[i];
            int cpt = i;
            
            for(i = 0; i<cpt; i++){
                item[i] = locaux[i];
            }
            
            return new DefaultComboBoxModel(item);
        } catch (SQLException ex) {
            Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
        }
        return new DefaultComboBoxModel();

    }
    
    private ComboBoxModel getComboBoxModelSalle(){
         try {
            // TODO add your handling code here:
            BDD bd = new BDD();
            bd.connect();
            ResultSet resultatsL = bd.select("SELECT nomLocal FROM Local");
            String[] locaux = new String[100];
            String[] Salle = new String[100];
            int cptl = 0;
            int cptS = 0;
            String req;
            while(resultatsL.next())
            {
                locaux[cptl] = resultatsL.getString(1);
                req = "SELECT nomSalle FROM Salle WHERE lieuSalle = '" +locaux[cptl]+"';";
                ResultSet resultatS = bd.select(req);
                Salle[cptS] = locaux[cptl];
                cptS++;
                while(resultatS.next()){
                    Salle[cptS] = "     ".concat(resultatS.getString(1));
                    cptS++;
                }
                cptl++;
            }

            
            String[] item = new String[cptS]; 
            

            
            
            for(int i = 0; i<cptS; i++){
                item[i] = Salle[i];
                System.out.println(item[i]);
            }
            
            return new DefaultComboBoxModel(item);
        } catch (SQLException ex) {
            Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
        }
        return new DefaultComboBoxModel();

}       
           
        



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelLocal;
    private javax.swing.JPanel jPanelOrdi;
    private javax.swing.JPanel jPanelRouteur;
    private javax.swing.JPanel jPanelSalle;
    private javax.swing.JPanel jPanelTablette;
    private javax.swing.JSpinner jSpinnerNBS;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFieldAL;
    private javax.swing.JTextField jTextFieldNL;
    // End of variables declaration//GEN-END:variables
}
