/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maven_java_project;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *Modification d'un composant dans la BDD
 * @author Florian
 */
public class Modifier extends javax.swing.JFrame {

    /**
     * Creates new form Modifier
     */
    public Modifier() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelModifier = new javax.swing.JLabel();
        jComboBoxSelectPrincModif = new javax.swing.JComboBox();
        jLabelSelectModif = new javax.swing.JLabel();
        jButtonValidModif = new javax.swing.JButton();
        jPanelModif = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanelLocal = new javax.swing.JPanel();
        jLabelLocalModif = new javax.swing.JLabel();
        jLabelNameLocal = new javax.swing.JLabel();
        jButtonValidLocal = new javax.swing.JButton();
        jTextFieldNameLocal = new javax.swing.JTextField();
        jPanelSalle = new javax.swing.JPanel();
        jLabelSalleModif = new javax.swing.JLabel();
        jLabelNameSalle = new javax.swing.JLabel();
        jTextFieldNameSalle = new javax.swing.JTextField();
        jButtonValidSalle = new javax.swing.JButton();
        jLabelEmplacementSalle = new javax.swing.JLabel();
        jComboBoxEmplacementSalle = new javax.swing.JComboBox();
        jPanelAppareil = new javax.swing.JPanel();
        jLabelAppModif = new javax.swing.JLabel();
        jLabelNameApp = new javax.swing.JLabel();
        jTextFieldNameApp = new javax.swing.JTextField();
        jLabelMacApp = new javax.swing.JLabel();
        jTextFieldMacApp = new javax.swing.JTextField();
        jLabelEmpApp = new javax.swing.JLabel();
        jLabelOsApp = new javax.swing.JLabel();
        jLabelActiveApp = new javax.swing.JLabel();
        jButtonValidAppModif = new javax.swing.JButton();
        jComboBoxEmplacementApp = new javax.swing.JComboBox();
        jComboBoxOsApp = new javax.swing.JComboBox();
        jComboBoxActiveApp = new javax.swing.JComboBox();
        jLabelFirmApp = new javax.swing.JLabel();
        jTextFieldFirmModif = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modifier un élément");

        jLabelModifier.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelModifier.setText("Modifier");

        jComboBoxSelectPrincModif.setModel(getComboBoxModelApp());
        jComboBoxSelectPrincModif.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxSelectPrincModifItemStateChanged(evt);
            }
        });
        jComboBoxSelectPrincModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectPrincModifActionPerformed(evt);
            }
        });

        jLabelSelectModif.setText("Sélectionner ce que vous voulez modifier...");

        jButtonValidModif.setText("Valider");
        jButtonValidModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidModifActionPerformed(evt);
            }
        });

        jPanelModif.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jPanelModif.add(jPanel2, "card2");

        jPanelLocal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelLocalModif.setText("Modifier les propriétés du local");

        jLabelNameLocal.setText("Nom du local :");

        jButtonValidLocal.setText("Valider");
        jButtonValidLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidLocalActionPerformed(evt);
            }
        });

        jTextFieldNameLocal.setText(nom());
        jTextFieldNameLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameLocalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLocalLayout = new javax.swing.GroupLayout(jPanelLocal);
        jPanelLocal.setLayout(jPanelLocalLayout);
        jPanelLocalLayout.setHorizontalGroup(
            jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLocalLayout.createSequentialGroup()
                .addGap(91, 414, Short.MAX_VALUE)
                .addComponent(jButtonValidLocal)
                .addGap(112, 112, 112))
            .addGroup(jPanelLocalLayout.createSequentialGroup()
                .addGroup(jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLocalLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabelLocalModif))
                    .addGroup(jPanelLocalLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabelNameLocal)
                        .addGap(89, 89, 89)
                        .addComponent(jTextFieldNameLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanelLocalLayout.setVerticalGroup(
            jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLocalModif)
                .addGap(74, 74, 74)
                .addGroup(jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameLocal)
                    .addComponent(jTextFieldNameLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jButtonValidLocal)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jPanelModif.add(jPanelLocal, "local");

        jPanelSalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSalleModif.setText("Modifier une salle");

        jLabelNameSalle.setText("Nom de la salle :");

        jTextFieldNameSalle.setText((String)jComboBoxSelectPrincModif.getSelectedItem());

        jButtonValidSalle.setText("Valider");
        jButtonValidSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidSalleActionPerformed(evt);
            }
        });

        jLabelEmplacementSalle.setText("Emplacement :");

        jComboBoxEmplacementSalle.setModel(getComboBoxModelLocal());

        javax.swing.GroupLayout jPanelSalleLayout = new javax.swing.GroupLayout(jPanelSalle);
        jPanelSalle.setLayout(jPanelSalleLayout);
        jPanelSalleLayout.setHorizontalGroup(
            jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalleLayout.createSequentialGroup()
                .addGroup(jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSalleLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabelSalleModif))
                    .addGroup(jPanelSalleLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNameSalle)
                            .addComponent(jLabelEmplacementSalle))
                        .addGap(76, 76, 76)
                        .addGroup(jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNameSalle, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jComboBoxEmplacementSalle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonValidSalle)
                .addGap(84, 84, 84))
        );
        jPanelSalleLayout.setVerticalGroup(
            jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSalleModif)
                .addGap(63, 63, 63)
                .addGroup(jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameSalle)
                    .addComponent(jTextFieldNameSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmplacementSalle)
                    .addComponent(jComboBoxEmplacementSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jButtonValidSalle)
                .addGap(86, 86, 86))
        );

        jPanelModif.add(jPanelSalle, "salle");

        jPanelAppareil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelAppModif.setText("Modifier un appareil");

        jLabelNameApp.setText("Nom de l'appareil :");

        jLabelMacApp.setText("Adresse MAC :");

        jLabelEmpApp.setText("Emplacement :");

        jLabelOsApp.setText("Système d'exploitation :");

        jLabelActiveApp.setText("Activer / Désactiver :");

        jButtonValidAppModif.setText("Valider");
        jButtonValidAppModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidAppModifActionPerformed(evt);
            }
        });

        jComboBoxEmplacementApp.setModel(getComboBoxModelSalle());

        jComboBoxOsApp.setModel(getComoBoxModelInit());

        jComboBoxActiveApp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        jLabelFirmApp.setText("Firmware :");

        javax.swing.GroupLayout jPanelAppareilLayout = new javax.swing.GroupLayout(jPanelAppareil);
        jPanelAppareil.setLayout(jPanelAppareilLayout);
        jPanelAppareilLayout.setHorizontalGroup(
            jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAppareilLayout.createSequentialGroup()
                .addGroup(jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAppareilLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabelAppModif))
                    .addGroup(jPanelAppareilLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAppareilLayout.createSequentialGroup()
                                .addGroup(jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNameApp)
                                    .addComponent(jLabelMacApp)
                                    .addComponent(jLabelEmpApp)
                                    .addComponent(jLabelOsApp))
                                .addGap(59, 59, 59)
                                .addGroup(jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNameApp, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMacApp)
                                    .addComponent(jComboBoxEmplacementApp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxOsApp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelAppareilLayout.createSequentialGroup()
                                    .addComponent(jLabelActiveApp)
                                    .addGap(59, 59, 59)
                                    .addComponent(jComboBoxActiveApp, 0, 115, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelAppareilLayout.createSequentialGroup()
                                    .addComponent(jLabelFirmApp)
                                    .addGap(123, 123, 123)
                                    .addComponent(jTextFieldFirmModif)
                                    .addGap(119, 119, 119))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAppareilLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonValidAppModif)
                                    .addGap(57, 57, 57))))))
                .addGap(70, 70, 70))
        );
        jPanelAppareilLayout.setVerticalGroup(
            jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAppareilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAppModif)
                .addGap(34, 34, 34)
                .addGroup(jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameApp)
                    .addComponent(jTextFieldNameApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMacApp)
                    .addComponent(jTextFieldMacApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmpApp)
                    .addComponent(jComboBoxEmplacementApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOsApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOsApp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirmApp)
                    .addComponent(jTextFieldFirmModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAppareilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelActiveApp)
                    .addComponent(jComboBoxActiveApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButtonValidAppModif)
                .addGap(63, 63, 63))
        );

        jPanelModif.add(jPanelAppareil, "appareil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jComboBoxSelectPrincModif, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButtonValidModif))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabelSelectModif))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(jLabelModifier)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelModif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelModifier)
                .addGap(28, 28, 28)
                .addComponent(jLabelSelectModif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSelectPrincModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonValidModif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanelModif, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidModifActionPerformed
        // TODO add your handling code here:
        String valueComboBox = (String)jComboBoxSelectPrincModif.getSelectedItem();
        if(valueComboBox.charAt(0) != ' '){
           ((CardLayout)jPanelModif.getLayout()).show(jPanelModif,"local");
        }
        else if(valueComboBox.length() > 9){
            jComboBoxOsApp.setModel(getComboBoxModelTypeOs());
            if(valueComboBox.charAt(8) == ' '){
           ((CardLayout)jPanelModif.getLayout()).show(jPanelModif,"appareil");
            }
            else{
                ((CardLayout)jPanelModif.getLayout()).show(jPanelModif,"salle");
            }
        }
        else{
           ((CardLayout)jPanelModif.getLayout()).show(jPanelModif,"salle");
        }
        System.out.println(valueComboBox);    
    }//GEN-LAST:event_jButtonValidModifActionPerformed

    private void jTextFieldNameLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameLocalActionPerformed

    private void jComboBoxSelectPrincModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectPrincModifActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxSelectPrincModifActionPerformed

    private void jButtonValidLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidLocalActionPerformed
        // TODO add your handling code here:
        String nomLocal = jTextFieldNameLocal.getText();
        Controleur ctrl = new Controleur();
        ctrl.modifierLocal(nom(), nomLocal);
        javax.swing.JOptionPane.showMessageDialog(null,"Le local a bien été mis à jour dans la base !", "Succès", JOptionPane.PLAIN_MESSAGE); 
        Principal princ = new Principal();
        princ.setLocationRelativeTo(null);
        this.setVisible(false);
        princ.setVisible(true); 
        
    }//GEN-LAST:event_jButtonValidLocalActionPerformed

    private void jComboBoxSelectPrincModifItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxSelectPrincModifItemStateChanged
        // TODO add your handling code here:
        jTextFieldNameLocal.setText(nom());
        jTextFieldNameSalle.setText(nom());
    }//GEN-LAST:event_jComboBoxSelectPrincModifItemStateChanged

    private void jButtonValidSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidSalleActionPerformed
        // TODO add your handling code here:
        String nomSalle = jTextFieldNameSalle.getText();
        Controleur ctrl = new Controleur();
        ctrl.modifierSalle(nom(), nomSalle, enleverEspace((String)jComboBoxEmplacementSalle.getSelectedItem()));
        javax.swing.JOptionPane.showMessageDialog(null,"La salle a bien été mis à jour dans la base !", "Succès", JOptionPane.PLAIN_MESSAGE); 
        Principal princ = new Principal();
        princ.setLocationRelativeTo(null);
        this.setVisible(false);
        princ.setVisible(true);         
    }//GEN-LAST:event_jButtonValidSalleActionPerformed

    private void jButtonValidAppModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidAppModifActionPerformed
        // TODO add your handling code here:
        String nomApp = jTextFieldNameApp.getText();
        String emp = enleverEspace((String)jComboBoxEmplacementApp.getSelectedItem());
        String sysOs = (String)jComboBoxOsApp.getSelectedItem();
        String firm = jTextFieldFirmModif.getText();
        Controleur ctrl = new Controleur();
        if("false".equals((String)jComboBoxActiveApp.getSelectedItem())){
            ctrl.desactiverApp(nom());
        }
        else{
            ctrl.activerApp(nom());
        }
        ctrl.modifierApp(nom(), nomApp, emp, sysOs, firm);
        javax.swing.JOptionPane.showMessageDialog(null,"L'appareil a bien été mis à jour dans la base !", "Succès", JOptionPane.PLAIN_MESSAGE); 
        Principal princ = new Principal();
        princ.setLocationRelativeTo(null);
        this.setVisible(false);
        princ.setVisible(true);             
    }//GEN-LAST:event_jButtonValidAppModifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifier().setVisible(true);
            }
        });
    }

    private ComboBoxModel getComboBoxModelApp(){
        int i = 0;
        int j =0;
        int k = 0;
        int idx = 0;
        
        Controleur ctrl = new Controleur();
        List<Local> listLocal = ctrl.getListeLocaux();
        List<Salle> listSalles = ctrl.getListeSalles();
        String[] item = new String[listLocal.size()+ctrl.getListeSalles().size()+ctrl.getListeApp().size()];
        while (i < listLocal.size()) {
            item[idx] = listLocal.get(i).getNomLocal();
            idx++;
            while (j < listLocal.get(i).getListeSalle().size()) {
                item[idx] = "     ".concat(listLocal.get(i).getListeSalle().get(j).getNomSalle());
                idx++;
                while (k < listSalles.get(ctrl.chercherNomListeSalle(listLocal.get(i).getListeSalle().get(j).getNomSalle())).getListeApp().size()) {
                    item[idx] = "         ".concat(listSalles.get(ctrl.chercherNomListeSalle(listLocal.get(i).getListeSalle().get(j).getNomSalle())).getListeApp().get(k).getNomApp()); // C'est du génie !!!!
                    idx++;
                    k++;
                }
                k = 0;
                j++;
            }
            j = 0;
            i++;
        }
        return new DefaultComboBoxModel(item);  
    }
    
    
    private String enleverEspace(String chaine){
        while(chaine.charAt(0) == ' '){
            chaine = chaine.substring(1);
        }
        return chaine;
    }
    
    
    private ComboBoxModel getComboBoxModelLocal() {
        Controleur ctrl = new Controleur();
        List<Local> listLocal = ctrl.getListeLocaux();
        String[] item = new String[listLocal.size()];
        for (int i = 0; i < listLocal.size(); i++) {
            item[i] = listLocal.get(i).getNomLocal();
        }

        return new DefaultComboBoxModel(item);
    }
    
    
private ComboBoxModel getComboBoxModelSalle(){
        int i = 0;
        int j = 0;
        int k = 0;
        Controleur ctrl = new Controleur();
        List<Local> listLocal = ctrl.getListeLocaux();
        String[] item = new String[listLocal.size()+ctrl.getListeSalles().size()];
        while (i < listLocal.size()) {
            item[k] = listLocal.get(i).getNomLocal();
            k++;
            while (j < listLocal.get(i).getListeSalle().size()) {
                item[k] = "     ".concat(listLocal.get(i).getListeSalle().get(j).getNomSalle());
                j++;
                k++;
            }
            j= 0;
            i++;
        }
        
        return new DefaultComboBoxModel(item);        

}       


private ComboBoxModel getComoBoxModelInit(){
    String item[] = {"  "};
    return new DefaultComboBoxModel(item);
}
private ComboBoxModel getComboBoxModelTypeOs(){
    Controleur ctrl = new Controleur();
    System.out.println(nom());
    String type = ctrl.getListeApp().get(ctrl.chercherNomListeApp(nom())).getTypeApp();
    String[] item = new String[3];
    if("     Ordinateur".equals(type)){
        item[0] = "Windows 7";
        item[1] = "Linux";
        item[2] = "MacOs";        
    }
    else if("     Tablette".equals(type)){
        item[0] = "Android";
        item[1] = "iOs";
        item[2] = "WindowsPhone";    
    }
    else{
        item[0] = "CiscoOS";
    }
    return new DefaultComboBoxModel(item);        
}

    private String nom(){
        return enleverEspace((String)jComboBoxSelectPrincModif.getSelectedItem());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValidAppModif;
    private javax.swing.JButton jButtonValidLocal;
    private javax.swing.JButton jButtonValidModif;
    private javax.swing.JButton jButtonValidSalle;
    private javax.swing.JComboBox jComboBoxActiveApp;
    private javax.swing.JComboBox jComboBoxEmplacementApp;
    private javax.swing.JComboBox jComboBoxEmplacementSalle;
    private javax.swing.JComboBox jComboBoxOsApp;
    private javax.swing.JComboBox jComboBoxSelectPrincModif;
    private javax.swing.JLabel jLabelActiveApp;
    private javax.swing.JLabel jLabelAppModif;
    private javax.swing.JLabel jLabelEmpApp;
    private javax.swing.JLabel jLabelEmplacementSalle;
    private javax.swing.JLabel jLabelFirmApp;
    private javax.swing.JLabel jLabelLocalModif;
    private javax.swing.JLabel jLabelMacApp;
    private javax.swing.JLabel jLabelModifier;
    private javax.swing.JLabel jLabelNameApp;
    private javax.swing.JLabel jLabelNameLocal;
    private javax.swing.JLabel jLabelNameSalle;
    private javax.swing.JLabel jLabelOsApp;
    private javax.swing.JLabel jLabelSalleModif;
    private javax.swing.JLabel jLabelSelectModif;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAppareil;
    private javax.swing.JPanel jPanelLocal;
    private javax.swing.JPanel jPanelModif;
    private javax.swing.JPanel jPanelSalle;
    private javax.swing.JTextField jTextFieldFirmModif;
    private javax.swing.JTextField jTextFieldMacApp;
    private javax.swing.JTextField jTextFieldNameApp;
    private javax.swing.JTextField jTextFieldNameLocal;
    private javax.swing.JTextField jTextFieldNameSalle;
    // End of variables declaration//GEN-END:variables
}


